{
 "title": "SGW",
 "description": "Stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backends Health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "com_opster_mclb_cluster_health_backends"
    }
   ]
  },
  {
   "title": "Success Rate ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(com_opster_mclb_new_total_reactor_netty_http_client_status_total{status=\"200\"}[2m])) / sum(rate(com_opster_mclb_new_total_reactor_netty_http_client_status_total[2m])) "
    }
   ]
  },
  {
   "title": "Average Response Time ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_received_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_received_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_sent_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_sent_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_server_internal_request_processing_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_internal_request_processing_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_server_internal_response_processing_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_internal_response_processing_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_received_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_received_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_sent_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_sent_time_seconds_count[$__interval])))"
    }
   ]
  },
  {
   "title": "Loaded Backends",
   "type": "singlestat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "com_opster_mclb_loadedBackend1" }
   ]
  },
  {
   "title": "Total Request per Min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(com_opster_mclb_new_total_reactor_netty_http_server_requests_total[1m])) by (job)"
    }
   ]
  },
  {
   "title": "Requests Rate ",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_opster_mclb_new_total_reactor_netty_http_server_requests_total[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operation Total Time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "sum((rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_received_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_received_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_sent_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_sent_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_server_internal_request_processing_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_internal_request_processing_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_server_internal_response_processing_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_internal_response_processing_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_received_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_received_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_sent_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_sent_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_operation_reactor_netty_http_server_elastic_search_took_seconds_sum[$__interval]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_elastic_search_took_seconds_count[$__interval]))) by (operation_type)"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Operations/s" }
   ],
   "targets": [
    {
     "expr": "com_opster_mclb_new_operation_reactor_netty_http_server_data_received_bytes_sum{job='mclb'}/ com_opster_mclb_new_operation_reactor_netty_http_server_data_received_bytes_count{job='mclb'}",
     "legendFormat": "{{operation_type}}"
    },
    {
     "expr": "com_opster_mclb_new_total_reactor_netty_http_server_data_received_bytes_sum{job='mclb'}/ com_opster_mclb_new_total_reactor_netty_http_server_data_received_bytes_count{job='mclb'}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Response Code Total",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(com_opster_mclb_new_tenant_operation_reactor_netty_http_client_status_total[1m])) by (status)",
     "legendFormat": "status: {{status}}"
    }
   ]
  },
  {
   "title": "Response processing time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(com_opster_mclb_new_total_reactor_netty_http_client_data_received_time_seconds_sum{service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_client_data_received_time_seconds_count{service='mclb'}[$__interval]) \n",
     "legendFormat": "received time"
    },
    {
     "expr": "rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_response_processing_seconds_sum {service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_response_processing_seconds_count{service='mclb'}[$__interval])\n",
     "legendFormat": "processing time"
    },
    {
     "expr": "rate(com_opster_mclb_new_total_reactor_netty_http_server_data_sent_time_seconds_sum{service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_data_sent_time_seconds_count{service='mclb'}[$__interval])\n\n",
     "legendFormat": "sent time"
    },
    {
     "expr": "(rate(com_opster_mclb_new_total_reactor_netty_http_client_data_received_time_seconds_sum{service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_client_data_received_time_seconds_count{service='mclb'}[$__interval])) + \n(rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_response_processing_seconds_sum {service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_response_processing_seconds_count{service='mclb'}[$__interval])) + \n(rate(com_opster_mclb_new_total_reactor_netty_http_server_data_sent_time_seconds_sum{service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_data_sent_time_seconds_count{service='mclb'}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Request processing time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(com_opster_mclb_new_total_reactor_netty_http_server_data_received_time_seconds_sum{service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_data_received_time_seconds_count{service='mclb'}[$__interval]) \n",
     "legendFormat": "receive time"
    },
    {
     "expr": "rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_request_processing_seconds_sum {service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_request_processing_seconds_count{service='mclb'}[$__interval])\n",
     "legendFormat": "processing time"
    },
    {
     "expr": "rate(com_opster_mclb_new_total_reactor_netty_http_client_data_sent_time_seconds_sum{service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_client_data_sent_time_seconds_count{service='mclb'}[$__interval])\n\n",
     "legendFormat": "sent time"
    },
    {
     "expr": "(rate(com_opster_mclb_new_total_reactor_netty_http_server_data_received_time_seconds_sum{service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_data_received_time_seconds_count{service='mclb'}[$__interval])) +\n(rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_request_processing_seconds_sum {service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_request_processing_seconds_count{service='mclb'}[$__interval])) +\n(rate(com_opster_mclb_new_total_reactor_netty_http_client_data_sent_time_seconds_sum{service='mclb'}[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_client_data_sent_time_seconds_count{service='mclb'}[$__interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Request Time / SGW Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "sum((rate(com_opster_mclb_new_total_reactor_netty_http_client_data_received_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_client_data_received_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_client_data_sent_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_client_data_sent_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_server_data_received_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_data_received_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_server_data_sent_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_data_sent_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_request_processing_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_request_processing_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_response_processing_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_response_processing_seconds_count[$__interval]))) by (pod)",
     "legendFormat": "SGW Latency"
    },
    {
     "expr": "sum((rate(com_opster_mclb_new_total_reactor_netty_http_server_data_received_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_data_received_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_server_data_sent_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_data_sent_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_request_processing_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_request_processing_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_response_processing_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_internal_response_processing_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_client_data_received_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_client_data_received_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_client_data_sent_time_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_client_data_sent_time_seconds_count[$__interval])) + (rate(com_opster_mclb_new_total_reactor_netty_http_server_elastic_search_took_seconds_sum[$__interval]) / rate(com_opster_mclb_new_total_reactor_netty_http_server_elastic_search_took_seconds_count[$__interval]))) by (pod)",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "title": "Healthy Backends",
   "type": "graph",
   "description": "0/1 - 0 State Healthy , 1 state Not Healthy",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(com_opster_mclb_cluster_health_backends[1m])",
     "legendFormat": "Backend: {{backend}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound Per Operation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_received_bytes_sum[1m]) / rate(com_opster_mclb_new_operation_reactor_netty_http_client_data_received_bytes_count[1m]) + rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_received_bytes_sum[1m]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_received_bytes_count[1m])) by (pod,operation_type)",
       "legendFormat": "{{pod}} - {{operation_type}}"
      }
     ]
    },
    {
     "title": "Inbound Per Operation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_sent_bytes_sum[1m]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_sent_bytes_count[1m]) + rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_received_bytes_sum[1m]) / rate(com_opster_mclb_new_operation_reactor_netty_http_server_data_received_bytes_count[1m])) by (pod,operation_type)",
       "legendFormat": "pod: {{pod}} op: {{operation_type}}"
      }
     ]
    },
    {
     "title": "Request Total ",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(com_opster_mclb_new_total_reactor_netty_http_server_requests_total[1m])",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Request Total Per Tenant",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(com_opster_mclb_new_tenant_operation_reactor_netty_http_server_requests_total[5m])) by (pod,tenant)",
       "legendFormat": "pod: {{pod}} Tenant: {{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM memory Used",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "bytes", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "sum(com_opster_mclb_jvm_memory_used_bytes) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Committed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum(com_opster_mclb_jvm_memory_committed_bytes) by (area,pod) ",
       "legendFormat": "{{pod}} {{area}}"
      }
     ]
    },
    {
     "title": "Load average",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "com_opster_mclb_system_load_average_1m",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percent", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"opster\", pod=~\"mclb.*\", container!=\"POD\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Pause Count",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "s", "label": "GCs" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_opster_mclb_jvm_gc_pause_seconds_count[1m])) by (cause)",
       "legendFormat": "{{cause}}"
      }
     ]
    },
    {
     "title": "GC Young/Old Allocation Change",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "bytes", "label": "GCs" }
     ],
     "targets": [
      {
       "expr": "sum(rate(com_opster_mclb_jvm_gc_memory_allocated_bytes_total[1m])) by (pod)",
       "legendFormat": "{{pod}} young"
      },
      {
       "expr": "sum(rate(com_opster_mclb_jvm_gc_memory_promoted_bytes_total[1m])) by (pod)",
       "legendFormat": "{{pod}} old"
      }
     ]
    },
    {
     "title": "Thread State",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "com_opster_mclb_jvm_threads_states_threads",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  }
 ]
}